// <auto-generated />
using CustomAuthTestWithDB.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CustomAuthTestWithDB.Migrations
{
    [DbContext(typeof(UserDbContext))]
    [Migration("20251110222519_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("CustomAuthTestWithDB.Models.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserAccounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "weather",
                            UserName = "weather"
                        },
                        new
                        {
                            Id = 2,
                            Password = "counter",
                            UserName = "counter"
                        },
                        new
                        {
                            Id = 3,
                            Password = "god",
                            UserName = "god"
                        });
                });

            modelBuilder.Entity("CustomAuthTestWithDB.Models.UserAccountPolicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserPolicy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserAccountPolicies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsEnabled = true,
                            UserAccountId = 1,
                            UserPolicy = "VIEW_WEATHER"
                        },
                        new
                        {
                            Id = 2,
                            IsEnabled = false,
                            UserAccountId = 1,
                            UserPolicy = "VIEW_COUNTER"
                        },
                        new
                        {
                            Id = 3,
                            IsEnabled = false,
                            UserAccountId = 2,
                            UserPolicy = "VIEW_WEATHER"
                        },
                        new
                        {
                            Id = 4,
                            IsEnabled = true,
                            UserAccountId = 2,
                            UserPolicy = "VIEW_COUNTER"
                        },
                        new
                        {
                            Id = 5,
                            IsEnabled = true,
                            UserAccountId = 3,
                            UserPolicy = "VIEW_WEATHER"
                        },
                        new
                        {
                            Id = 6,
                            IsEnabled = true,
                            UserAccountId = 3,
                            UserPolicy = "VIEW_COUNTER"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
